function slugify(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

export const products = [
  // ===== LAPTOPS =====
  {
    id: "lap-001",
    slug: "dell-inspiron-15",
    category: "Laptop",
    name: "Dell Inspiron 15",
    specs: "Intel i5 12th Gen, 8GB RAM, 512GB SSD",
    pricePerDay: 349,
    image: "/images/laptop-placeholder.svg",
    tag: "Budget Friendly",
  },
  {
    id: "lap-002",
    slug: "dell-xps-15",
    category: "Laptop",
    name: "Dell XPS 15",
    specs: "Intel i7 13th Gen, 16GB RAM, 512GB SSD",
    pricePerDay: 599,
    image: "/images/laptop-placeholder.svg",
    tag: "Popular",
  },
  {
    id: "lap-003",
    slug: "hp-pavilion-14",
    category: "Laptop",
    name: "HP Pavilion 14",
    specs: "Intel i5 12th Gen, 8GB RAM, 256GB SSD",
    pricePerDay: 379,
    image: "/images/laptop-placeholder.svg",
    tag: "Everyday Use",
  },
  {
    id: "lap-004",
    slug: "hp-pavilion-gaming-15",
    category: "Laptop",
    name: "HP Pavilion Gaming 15",
    specs: "Ryzen 5, GTX 1650 4GB, 16GB RAM",
    pricePerDay: 549,
    image: "/images/laptop-placeholder.svg",
    tag: "Gaming",
  },
  {
    id: "lap-005",
    slug: "lenovo-thinkpad-e14",
    category: "Laptop",
    name: "Lenovo ThinkPad E14",
    specs: "Intel i5 12th Gen, 8GB RAM, 512GB SSD",
    pricePerDay: 449,
    image: "/images/laptop-placeholder.svg",
    tag: "Business",
  },
  {
    id: "lap-006",
    slug: "lenovo-ideapad-slim-5",
    category: "Laptop",
    name: "Lenovo IdeaPad Slim 5",
    specs: "Ryzen 7, 16GB RAM, 512GB SSD",
    pricePerDay: 499,
    image: "/images/laptop-placeholder.svg",
    tag: "Slim & Light",
  },
  // {
  //   id: "lap-007",
  //   category: "Laptop",
  //   name: "MacBook Air M2",
  //   specs: "Apple M2, 8GB RAM, 256GB SSD",
  //   pricePerDay: 799,
  //   image: "/images/laptop-placeholder.svg",
  //   tag: "Premium",
  // },
  // {
  //   id: "lap-008",
  //   category: "Laptop",
  //   name: "MacBook Pro 14\" M3",
  //   specs: "Apple M3, 16GB RAM, 512GB SSD",
  //   pricePerDay: 1199,
  //   image: "/images/laptop-placeholder.svg",
  //   tag: "Pro Grade",
  // },

  // ===== MONITORS =====
  {
    id: "mon-001",
    slug: "dell-24-fhd-monitor",
    category: "Monitor",
    name: "Dell 24\" FHD Monitor",
    specs: "1920x1080, IPS, 75Hz",
    pricePerDay: 129,
    image: "/images/monitor-placeholder.svg",
    tag: "Everyday Use",
  },
  {
    id: "mon-002",
    slug: "lg-ultrawide-27",
    category: "Monitor",
    name: "LG UltraWide 27\"",
    specs: "2560x1080, IPS, 75Hz",
    pricePerDay: 229,
    image: "/images/monitor-placeholder.svg",
    tag: "Productivity",
  },
  {
    id: "mon-003",
    slug: "samsung-4k-32",
    category: "Monitor",
    name: "Samsung 4K 32\"",
    specs: "3840x2160, VA Panel, HDR10",
    pricePerDay: 349,
    image: "/images/monitor-placeholder.svg",
    tag: "4K",
  },
  {
    id: "mon-004",
    slug: "benq-designer-24",
    category: "Monitor",
    name: "BenQ Designer 24\"",
    specs: "1920x1080, IPS, 100% sRGB",
    pricePerDay: 179,
    image: "/images/monitor-placeholder.svg",
    tag: "Design",
  },
  // {
  //   id: "mon-005",
  //   category: "Monitor",
  //   name: "ASUS TUF Gaming 27\"",
  //   specs: "2560x1440, 165Hz, 1ms Response",
  //   pricePerDay: 299,
  //   image: "/images/monitor-placeholder.svg",
  //   tag: "Gaming",
  // },
];