import { Laptop, Monitor, Apple, Server, Printer, Tv } from "lucide-react";

export const servicesData = {
  "laptop-rentals": {
    Icon: Laptop,
    iconFrom: "from-indigo-400",
    iconTo: "to-indigo-600",
    badge: "Laptop Rentals",
    title: "Business Laptops, Ready When You Need Them",
    intro:
      "A wide range of business laptops from Dell, HP, Lenovo, and Apple MacBooks, suitable for everything from general office work to high-end creative tasks.",
    highlights: [
      "Latest models from Dell, HP, Lenovo & Apple",
      "Flexible rental durations — daily, weekly, monthly",
      "Pre-configured with essential software on request",
      "Free doorstep delivery & pickup",
      "On-call servicing support included",
      "Bulk rental discounts for teams & enterprises",
    ],
    useCases: [
      "Remote teams",
      "Startups & SMEs",
      "Creative professionals",
      "Students & exam prep",
      "Short-term projects",
      "Corporate onboarding",
    ],
  },
  "desktop-rentals": {
    Icon: Monitor,
    iconFrom: "from-cyan-400",
    iconTo: "to-cyan-600",
    badge: "Desktop Rentals",
    title: "Reliable Desktops for Every Workspace",
    intro:
      "Reliable desktops in standard and high-performance configurations, ideal for offices, design studios, and development teams.",
    highlights: [
      "Standard & high-performance configurations available",
      "Suitable for offices, studios & dev teams",
      "Monitor, keyboard & mouse bundles available",
      "Quality-checked before every rental",
      "Quick replacement in case of issues",
      "Custom configs available for specific workloads",
    ],
    useCases: [
      "Design studios",
      "Development teams",
      "Office workstations",
      "Training centers",
      "Call centers",
      "Temporary setups",
    ],
  },
  "apple-rentals": {
    Icon: Apple,
    iconFrom: "from-gray-500",
    iconTo: "to-gray-800",
    badge: "Apple Device Rentals",
    title: "Premium MacBooks & iMacs, On Demand",
    intro:
      "Premium MacBooks and iMacs for creative professionals, agencies, and businesses seeking exceptional performance and style.",
    highlights: [
      "Latest MacBook Air, MacBook Pro & iMac models",
      "Ideal for design, video editing & development",
      "Genuine Apple chargers & accessories included",
      "Pre-configured with creative software on request",
      "Flexible short and long-term rental plans",
      "Dedicated Apple servicing support",
    ],
    useCases: [
      "Design agencies",
      "Video editors",
      "Creative freelancers",
      "Marketing teams",
      "Software developers",
      "Corporate executives",
    ],
  },
  "server-rentals": {
    Icon: Server,
    iconFrom: "from-purple-400",
    iconTo: "to-purple-600",
    badge: "Server Rentals",
    title: "Enterprise Servers for Short-Term Infrastructure",
    intro:
      "Enterprise-grade servers tailored for hosting, database management, development, and short-term infrastructure needs.",
    highlights: [
      "Rack & tower server options available",
      "Suitable for hosting, databases & dev/test environments",
      "Flexible short-term infrastructure scaling",
      "On-site setup & configuration support",
      "24/7 technical support available",
      "Secure data handling practices",
    ],
    useCases: [
      "IT infrastructure teams",
      "Hosting providers",
      "Database management",
      "Dev & test environments",
      "Events & exhibitions",
      "Disaster recovery setups",
    ],
  },
  "printer-rentals": {
    Icon: Printer,
    iconFrom: "from-pink-400",
    iconTo: "to-pink-600",
    badge: "Printer Rentals",
    title: "High-Speed Printers & Copiers for Business",
    intro:
      "High-speed multifunction printers and copiers for bulk document printing, scanning, and copying in business environments.",
    highlights: [
      "Multifunction printers — print, scan & copy",
      "High-speed bulk printing capability",
      "Toner & maintenance included in rental",
      "Suitable for offices, events & exhibitions",
      "Quick replacement in case of downtime",
      "Flexible monthly rental plans",
    ],
    useCases: [
      "Corporate offices",
      "Events & exhibitions",
      "Print shops",
      "Educational institutes",
      "Co-working spaces",
      "Temporary office setups",
    ],
  },
  "smart-tv-rentals": {
    Icon: Tv,
    iconFrom: "from-amber-400",
    iconTo: "to-amber-600",
    badge: "Smart TV Rentals",
    title: "Large-Format Displays for Impactful Presentations",
    intro:
      "Large-format LED and Smart TVs for impactful presentations at conferences, exhibitions, and corporate events.",
    highlights: [
      "Wide range of screen sizes available",
      "4K & Full HD display options",
      "Wall-mount & stand setup support",
      "Ideal for conferences, exhibitions & events",
      "On-site installation & technical support",
      "Short-term & event-based rental plans",
    ],
    useCases: [
      "Corporate conferences",
      "Trade exhibitions",
      "Product launches",
      "Training sessions",
      "Retail displays",
      "Wedding & event venues",
    ],
  },
};
